version: '3'

services:
  pro-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./api.yaml:/app/api.yaml
      - ./data/:/app/data:rw
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
